version: "3.9"
services:
  backend:
    build:
      context: ../backend
    container_name: elderly-backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../backend/app:/app/app:rw
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').getcode()==200 else sys.exit(1)"]
      interval: 5s
      timeout: 2s
      retries: 10

  frontend:
    build:
      context: ../frontend
    container_name: elderly-frontend
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=
    volumes:
      - ../frontend:/usr/src/app:rw
    depends_on:
      backend:
        condition: service_healthy
